import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Jack High Lawn Bowls Manager",
  description: "Generated by Brent Edwards",
  icons: {
    icon: "/jackhigh_logo_tiny.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/jackhigh_logo_tiny.png" />
      </head>
      <body className="flex justify-center">
        <div className="w-full max-w-[750px] px-4">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
